# Generated by Django 5.0.2 on 2024-02-13 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='post_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('file', models.FileField(blank=True, upload_to='post_files/')),
                ('text_field_1', models.TextField(blank=True, max_length=5000)),
                ('text_field_2', models.TextField(blank=True, max_length=5000)),
                ('authors', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, to='mainSite.image')),
            ],
        ),
    ]
