# Generated by Django 5.0.2 on 2024-02-12 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(30)])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('problem_counter', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
