# Generated by Django 5.0.2 on 2024-02-14 10:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('latex_code', models.TextField()),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='problem_images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='problem_pdfs/')),
                ('difficulty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('genre', models.CharField(choices=[('geometry', 'Geometry'), ('combinatorics', 'Combinatorics'), ('numbertheory', 'Number Theory'), ('algebra', 'Algebra'), ('other', 'Other')], max_length=15)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemHint',
            fields=[
                ('hintId', models.AutoField(primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('hints', models.TextField()),
                ('latex_solution', models.TextField()),
                ('solution_pdf', models.FileField(blank=True, null=True, upload_to='hint_pdfs/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hintBase.problem')),
            ],
        ),
    ]
