# Generated by Django 5.0.2 on 2024-02-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hintBase', '0002_problem_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='pdf',
        ),
    ]
