# Generated by Django 5.0.2 on 2024-02-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hintBase', '0003_remove_problem_genre_remove_problem_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemhint',
            name='solution_pdf',
        ),
    ]
