# Generated by Django 5.0.6 on 2024-06-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hintBase', '0004_remove_problemhint_solution_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemhint',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemhint',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
