# Generated by Django 5.0.6 on 2024-06-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hintBase', '0006_problem_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
