# Generated by Django 5.0.6 on 2024-07-07 10:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hintBase', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hintBase.problem'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ratings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
