# Generated by Django 5.0.6 on 2024-07-04 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.DurationField()),
                ('theme', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='kolo_images/')),
                ('file', models.FileField(upload_to='kolo_files/')),
                ('level', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('tutors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
